module.exports = {
  "/" : "index",
  "/index" : "index",
  "/guest-houses": "guestHouses",
  "/error": "error",
  "/sign-in": "signIn",
  "/reset-password": "resetPassword",
  "/about-us": "aboutUs",
  "/apartment/:id": "viewApartment",
  "/contact-us": "contactUs",
  "/blogs": "blogs",
  "/blog/:id": "viewBlog",
  "guesthouse-seeker" : "guesthouseSeeker",
  "guesthouse-owner" : "guesthouseOwner",
  "guesthouse-admin" : "guesthouseAdmin",
  "guesthouse-employee" : "guesthouseEmployee",
};