module.exports = {
  "/" : "index",
  "/index" : "index",
  "/guest-houses": "guestHouses",
  "/error": "error",
  "/sign-in": "signIn",
  "/reset-password": "resetPassword",
  "/about-us": "aboutUs",
  "/apartment/:description/:id": "viewApartment",
  "/combo-apartment/:description/:id": "viewComboApartment",
  "/contact-us": "contactUs",
  "/blogs": "blogs",
  "/your-trip": "YourTrip",
  "/your-trip/:trip/:id": "ATrip",
  "/blog/:id": "viewBlog",
  "/my-account" : "myAccount",
  "/reset-password" : "resetPassword",
  "/terms-of-use" : "termsOfUse",
  "/privacy-policy" : "privacyPolicy"
};